// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnhP-CK9VzkH9RwK3z0uL3YisLDrrCx4o',
    appId: '1:962157158589:web:563930b5fcb5b4aae117d4',
    messagingSenderId: '962157158589',
    projectId: 'elevy-web-app',
    authDomain: 'elevy-web-app.firebaseapp.com',
    storageBucket: 'elevy-web-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjl28mlbGe2_4_iaBidM31nDyB2z3AraM',
    appId: '1:962157158589:android:56be4e2a7348513ce117d4',
    messagingSenderId: '962157158589',
    projectId: 'elevy-web-app',
    storageBucket: 'elevy-web-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArXAeEkkCPYu3yZ_v5JgYBjmXoDrszOrU',
    appId: '1:962157158589:ios:c0486b0445000640e117d4',
    messagingSenderId: '962157158589',
    projectId: 'elevy-web-app',
    storageBucket: 'elevy-web-app.appspot.com',
    iosBundleId: 'com.example.elevyWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArXAeEkkCPYu3yZ_v5JgYBjmXoDrszOrU',
    appId: '1:962157158589:ios:0131bdddbf55e892e117d4',
    messagingSenderId: '962157158589',
    projectId: 'elevy-web-app',
    storageBucket: 'elevy-web-app.appspot.com',
    iosBundleId: 'com.example.elevyWebApp.RunnerTests',
  );
}
